#! /usr/bin/python

import sys, os, getopt, re
import numpy as np
from pynumpdb.anm import anmMove

def version():
  print """
  anm_move ver. 0.1
  coded by Shiqiao Du in 12,Jun,2010

  ver. 0.2 14,Jun,2010
  modified to set maxd in proportion to the frequency
  """

def usage():
  print """
  usage: <this script> pdbfile eigen_log [options]

  eigen_log can be generated by ANM fortran program as follows
  ############################################################
  7      0.18609930    

  -0.0048   -0.0148    0.0156
  -0.0074   -0.0106    0.0148
  -0.0078   -0.0054    0.0114
  -0.0110   -0.0038    0.0126
  -0.0102   -0.0054    0.0129
  -0.0055   -0.0063    0.0100
  -0.0043   -0.0042    0.0063
  ###########################################################
                                  

  options
  -h, --help: this massage
  -o, --out=out_file :  output to "out_file"
    default = "input_AA_BBB.pdb" AA is #mode and BBB is #step
  -b, --begin=b : extract from bth eigen mode  
    default = 7
  -n, --num=n : extract n eigen modes
    default = 6
  -d, --deviation=d : set max deviation to d angstrom
    default = calculate by frequency
  -s, --step=s : set step numbers by which the deviation will be splitted
    default = 30
  """
  sys.exit(2)

if __name__ == "__main__":
  # initialization
  version()
  beig = 7
  neig = 6
  maxd = None
  step = 30


  # get command line arguments
  try:
    pdb_file = sys.argv[1]
    eig_log = sys.argv[2]
    out_file = os.path.splitext(os.path.basename(pdb_file))[0]
  except:
    usage()

  try:
    opts, args = getopt.getopt(sys.argv[3:],"ho:b:n:d:s:", \
                  ["help","out=","begin=","num=","deviation=","step="])
  except IndexError,getopt.GetoptError:
    usage()

  for o,a in opts:
    if o in ("-h","--help"):
      usage()
    if o in ("-o","--out"):
      out_file = a
    if o in ("-b","--begin"):
      beig = int(a)
    if o in ("-n","--num"):
      neig = int(a)
    if o in ("-d","--deviation"):
      maxd = float(a)
    if o in ("-s","--step"):
      step = int(a)

  anmMove(pdb_file,eig_log,out_file,beig,neig,step,maxd)
